# Generated by Django 2.2.6 on 2019-12-06 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('rating', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=250)),
                ('type_icon', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('summary', models.CharField(blank=True, max_length=250)),
                ('sliders', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('image', models.CharField(default='avatar.png', max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('confirmed', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=250)),
                ('cart', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('ingredients', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=100)),
                ('type_order', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allofood.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('subtotal', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('telephone', models.IntegerField()),
                ('payed', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allofood.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allofood.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('rating', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allofood.Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allofood.User')),
            ],
        ),
    ]
